# Generated by Django 6.0.4 on 2026-04-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('user_name', models.CharField(max_length=100)),
                ('user_phone', models.CharField(max_length=20)),
                ('user_password', models.CharField(max_length=100)),
            ],
        ),
    ]
